"""Top-level orchestrator: [optional] unit tests -> [optional] preprocessing
-> trade_engine -> minute_snapshot -> [optional] report -> [optional] notebook.

Each invocation gets its own run directory (outputs/runs/run_<timestamp> by
default, or --run-name / an explicit --run-dir) so repeated runs with
different parameters don't clobber each other.

Run:
    python src/main.py
    python src/main.py --candidates-file data/candidates.parquet --skip-tests
    python src/main.py --hedge-threshold 0.05 --max-open-positions 3 --output-level full
    python src/main.py --output-level minimal
"""
import argparse
import json
import os
import sys
import time
from datetime import datetime, timezone

import pandas as pd

import preprocessing
import trade_engine
import minute_snapshot
import report

OUTPUT_LEVELS = ["minimal", "standard", "full"]


def run_unit_tests() -> bool:
    import pytest
    tests_dir = os.path.join(os.path.dirname(__file__), "..", "tests")
    exit_code = pytest.main(["-q", tests_dir])
    return exit_code == 0


def make_run_dir(runs_base: str, run_name: str = None) -> str:
    name = run_name or f"run_{datetime.now(timezone.utc).strftime('%Y%m%d_%H%M%S')}"
    run_dir = os.path.join(runs_base, name)
    os.makedirs(run_dir, exist_ok=True)
    return run_dir


def sibling_meta_path(candidates_path: str) -> str:
    """preprocessing.py writes candidates_meta.json next to candidates.parquet
    under the same stem; look for it there when reusing an existing file."""
    stem = os.path.splitext(candidates_path)[0]
    return f"{stem}_meta.json"


def build_minimal_summary(snapshot_df: pd.DataFrame, trades_df: pd.DataFrame,
                           hedge_trades_df: pd.DataFrame, cand: pd.DataFrame,
                           candidates_meta_path: str, initial_capital: float) -> dict:
    """Cheap path for --output-level minimal: works entirely on in-memory
    DataFrames (never writes trades.csv/hedge_trades.csv/minute_snapshot.csv
    to the run directory) and reuses report.py's pure analysis functions --
    the only file this mode produces is execution_summary.json."""
    snapshot, trades, hedge_trades = report.enrich_inputs(snapshot_df, trades_df, hedge_trades_df, cand)
    daily = report.build_daily_pnl(snapshot, trades, initial_capital)
    warnings = report.collect_data_quality_warnings(trades, hedge_trades, candidates_meta_path)
    risk_summary = report.compute_risk_summary(daily, trades, hedge_trades, snapshot, initial_capital, warnings)
    execution_summary = report.build_execution_summary(trades, hedge_trades, initial_capital)
    return {
        "risk_summary": risk_summary,
        "execution_summary": execution_summary.iloc[0].to_dict() if len(execution_summary) else {},
    }


# ---------------------------------------------------------------------------
# Notebook generation (hand-built nbformat v4 JSON -- avoids an nbformat dep)
# ---------------------------------------------------------------------------
def _code_cell(lines):
    return {"cell_type": "code", "execution_count": None, "metadata": {}, "outputs": [], "source": lines}


def _markdown_cell(lines):
    return {"cell_type": "markdown", "metadata": {}, "source": lines}


def generate_notebook(run_dir: str, notebook_path: str):
    cells = [
        _markdown_cell([
            "# Backtest Analysis\n", "\n",
            f"Run directory: `{os.path.basename(run_dir)}`\n", "\n",
            "Auto-generated by `main.py` (`--output-level full`). Run all cells.",
        ]),
        _markdown_cell(["## Run configuration"]),
        _code_cell([
            "import json, pandas as pd\n",
            "from IPython.display import Image\n",
            "with open('run_config.json') as f:\n",
            "    print(json.dumps(json.load(f), indent=2))\n",
        ]),
        _markdown_cell(["## Risk summary"]),
        _code_cell([
            "with open('risk_summary.json') as f:\n",
            "    risk_summary = json.load(f)\n",
            "print(json.dumps(risk_summary, indent=2))\n",
        ]),
        _markdown_cell(["## Execution summary"]),
        _code_cell(["pd.read_csv('execution_summary.csv').T\n"]),
        _markdown_cell(["## Daily PnL"]),
        _code_cell(["daily_pnl = pd.read_csv('daily_pnl.csv')\n", "daily_pnl\n"]),
        _markdown_cell(["## Option trades"]),
        _code_cell([
            "trades = pd.read_csv('trades.csv')\n",
            "print(f'{len(trades)} option trades')\n",
            "trades.head(20)\n",
        ]),
        _markdown_cell(["## Hedge trades"]),
        _code_cell([
            "hedge_trades = pd.read_csv('hedge_trades.csv')\n",
            "print(f'{len(hedge_trades)} hedge trades')\n",
            "hedge_trades.head(20)\n",
        ]),
        _markdown_cell(["## Greeks timeseries"]),
        _code_cell(["pd.read_csv('greeks_timeseries.csv').head()\n"]),
        _markdown_cell(["## NAV curve"]),
        _code_cell(["Image('nav_curve.png')\n"]),
        _markdown_cell(["## Drawdown curve"]),
        _code_cell(["Image('drawdown_curve.png')\n"]),
        _markdown_cell(["## Option PnL -- gross vs net of fees"]),
        _code_cell(["Image('options_pnl.png')\n"]),
        _markdown_cell(["## Hedge PnL -- gross vs net of fees"]),
        _code_cell(["Image('hedge_pnl.png')\n"]),
        _markdown_cell(["## Option PnL decomposition by greek"]),
        _code_cell(["Image('greek_pnl_decomposition.png')\n"]),
        _markdown_cell(["## Overall strategy PnL"]),
        _code_cell(["Image('overall_pnl.png')\n"]),
    ]
    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {"display_name": "Python 3", "language": "python", "name": "python3"},
            "language_info": {"name": "python", "version": "3"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }
    with open(notebook_path, "w") as f:
        json.dump(notebook, f, indent=1)


# ---------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Run the full sell-call backtest pipeline.")
    parser.add_argument("--input", default="./data/full_data_clean.parquet",
                         help="Raw cleaned parquet, used only if --candidates-file is not given.")
    parser.add_argument("--candidates-file", default=None,
                         help="Pre-built candidates.parquet -- if given, preprocessing is skipped.")
    parser.add_argument("--runs-dir", default="./outputs/runs")
    parser.add_argument("--run-name", default=None)
    parser.add_argument("--initial-capital", type=float, default=1_000_000.0)

    parser.add_argument("--skip-tests", action="store_true", help="Skip running the unit test suite first.")
    parser.add_argument("--output-level", choices=OUTPUT_LEVELS, default="standard",
                         help="minimal: execution_summary.json only. standard: full CSV/JSON/plot "
                              "report. full: standard + an analysis.ipynb notebook.")

    parser.add_argument("--hedge-threshold", type=float, default=trade_engine.HEDGE_THRESHOLD)
    parser.add_argument("--max-open-positions", type=int, default=trade_engine.MAX_OPEN_POSITIONS)
    parser.add_argument("--option-lot-size", type=float, default=trade_engine.OPTION_LOT_SIZE)
    parser.add_argument("--min-score", type=float, default=trade_engine.MIN_SCORE)
    parser.add_argument("--underlying-lot-size", type=float,
                         default=trade_engine.UNDERLYING_LOT_SIZE)

    parser.add_argument("--w-theta", type=float, default=None)
    parser.add_argument("--w-vega", type=float, default=None)
    parser.add_argument("--w-gamma", type=float, default=None)
    parser.add_argument("--w-spread", type=float, default=None)
    args = parser.parse_args()

    t0 = time.time()

    if not args.skip_tests:
        print("Running unit tests...")
        if not run_unit_tests():
            print("Unit tests FAILED -- aborting backtest run.")
            sys.exit(1)
        print("Unit tests passed.\n")
    else:
        print("Skipping unit tests (--skip-tests).\n")

    run_dir = make_run_dir(args.runs_dir, args.run_name)
    print(f"Run directory: {run_dir}")

    if args.candidates_file:
        candidates_path = args.candidates_file
        candidates_meta_path = sibling_meta_path(candidates_path)
        print(f"Using existing candidates file: {candidates_path} (preprocessing skipped)")
    else:
        candidates_path = os.path.join(run_dir, "candidates.parquet")
        candidates_meta_path = os.path.join(run_dir, "candidates_meta.json")
        print("Running preprocessing...")
        preprocessing.run(
            source=args.input, output=candidates_path, meta_output=candidates_meta_path,
            weights=preprocessing.ScoreWeights(
                w_theta=args.w_theta, w_vega=args.w_vega,
                w_gamma=args.w_gamma, w_spread=args.w_spread,
            ),
        )

    cand = pd.read_parquet(candidates_path)

    print("Running trade engine...")
    trades_df, hedge_trades_df = trade_engine.generate_trades(
        cand,
        hedge_threshold=args.hedge_threshold,
        max_open_positions=args.max_open_positions,
        option_lot_size=args.option_lot_size,
        min_score=args.min_score,
        underlying_lot_size=args.underlying_lot_size,
    )
    print(f"  {len(trades_df)} option trades, {len(hedge_trades_df)} hedge trades")

    print("Running minute snapshot...")
    snapshot_df = minute_snapshot.generate_minute_snapshot(
        cand, trades_df, hedge_trades_df, args.initial_capital)

    run_config = {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "candidates_file": candidates_path,
        "preprocessing_skipped": bool(args.candidates_file),
        "initial_capital": args.initial_capital,
        "hedge_threshold": args.hedge_threshold,
        "max_open_positions": args.max_open_positions,
        "option_lot_size": args.option_lot_size,
        "min_score": args.min_score,
        "underlying_lot_size": args.underlying_lot_size,
        "output_level": args.output_level,
        "unit_tests_run": not args.skip_tests,
    }

    if args.output_level == "minimal":
        # Only file written at this level: execution_summary.json. trades/
        # hedge_trades/minute_snapshot stay in memory and are never persisted.
        print("Building minimal execution_summary.json...")
        summary = build_minimal_summary(
            snapshot_df, trades_df, hedge_trades_df, cand,
            candidates_meta_path, args.initial_capital)
        summary["run_config"] = run_config
        with open(os.path.join(run_dir, "execution_summary.json"), "w") as f:
            json.dump(summary, f, indent=2)
    else:
        trades_path = os.path.join(run_dir, "trades.csv")
        hedge_trades_path = os.path.join(run_dir, "hedge_trades.csv")
        snapshot_path = os.path.join(run_dir, "minute_snapshot.csv")
        trades_df.to_csv(trades_path, index=False)
        hedge_trades_df.to_csv(hedge_trades_path, index=False)
        snapshot_df.to_csv(snapshot_path, index=False)

        with open(os.path.join(run_dir, "run_config.json"), "w") as f:
            json.dump(run_config, f, indent=2)

        print("Running full report (CSVs, risk summary, plots)...")
        report.run(
            snapshot_path=snapshot_path, trades_path=trades_path,
            hedge_trades_path=hedge_trades_path, candidates_path=candidates_path,
            candidates_meta_path=candidates_meta_path, output_dir=run_dir,
            initial_capital=args.initial_capital,
        )
        if args.output_level == "full":
            print("Generating analysis notebook...")
            generate_notebook(run_dir, os.path.join(run_dir, "analysis.ipynb"))

    elapsed = time.time() - t0
    print(f"\nDone in {elapsed:.1f}s. Outputs in {run_dir}/")


if __name__ == "__main__":
    main()
